master:
  clients:
    address: 0.0.0.0:4000
    insecure: true
  management: 
    address: localhost:4001
    insecure: true
files:
  address: 0.0.0.0:8000
  insecure: true
  directory: ui
nodes:
  - name: Default Server
    master: localhost:4001
    address: 0.0.0.0:3000
    insecure: true
    origins:
    - http://localhost
    rooms:
    - name: Long-term games!
      width: 1800
      height: 1800
      maxviruses: 29
      maxbacteria: 7
      maxsplit: 11
      minsplitmass: 65
      mergetime: 18
      sizemultiplier: 0.64
      speedmultiplier: 0.4
      startmass: 40
      maxpellets: 1800
    - name: The Desert!
      width: 2000
      height: 2000
      maxviruses: 8
      maxbacteria: 2
      maxsplit: 5
      minsplitmass: 65
      mergetime: 30
      sizemultiplier: 0.64
      speedmultiplier: 0.4
      startmass: 15
      maxpellets: 200
  - name: Experimental Server
    master: localhost:4001
    address: 0.0.0.0:3001
    insecure: true
    origins:
    - http://localhost
    rooms:
    - name: Split Fest!
      width: 1800
      height: 600
      maxviruses: 9
      maxbacteria: 9
      maxsplit: 22
      minsplitmass: 55
      mergetime: 3
      sizemultiplier: 0.69
      speedmultiplier: 0.55
      startmass: 80
      maxpellets: 500
    - name: Quick and silly!
      width: 1500
      height: 900
      maxviruses: 30
      maxbacteria: 8
      maxsplit: 11
      minsplitmass: 65
      mergetime: 18
      sizemultiplier: 0.64
      speedmultiplier: 0.45
      startmass: 80
      maxpellets: 2000
    - name: Oh god why
      width: 1800
      height: 18000
      maxviruses: 60
      maxbacteria: 25
      maxsplit: 50
      minsplitmass: 100
      mergetime: 1
      sizemultiplier: 0.64
      speedmultiplier: 0.4
      startmass: 10
      maxpellets: 1800