version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./cmd/master/Dockerfile
    ports:
     - "8000:8000"
  node:
    build:
      context: .
      dockerfile: ./cmd/node/Dockerfile
    ports:
      - "8001:8001"