version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./cmd/master/Dockerfile
    ports:
     - "8000:8000"
     - "4000:4000"
    networks:
      local:
        aliases:
          - master
  node:
    build:
      context: .
      dockerfile: ./cmd/node/Dockerfile
    ports:
      - "8001:8001"
    networks:
      local:

networks:
  local: