#!/bin/bash
#
# chkconfig: 35 90 12
# description: tb server
#

# Get function from functions library
. /etc/init.d/functions

# Start the service tb
start() {
        initlog -c "echo -n Starting tb server: "
        /root/tb master node files &
        ### Create the lock file ###
        touch /var/lock/subsys/tb
        success $"tb server startup"
        echo
}

# Restart the service tb
stop() {
        initlog -c "echo -n Stopping tb server: "
        killproc tb
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/tb
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status tb
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0